# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2807d3f73958df43e084a3dd41860c6a89c3a410fa363f0be783e3fde237d83ed12cf937ee6eea1121c407f59c5773c09708b8aa95b1c06ee6fb08daaaa0bf7b

test:
  secret_key_base: fe3af4ca9ac002b48b56ee1a164b02022eeae95734fb0a35e2b3a035310d8059a4c30d5f9daad2a35eff9ae3615389772e4782f1519055eba8286e136ca91de0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
